# paramètres globaux
train: False # lancer une routine d'entraînement ?
old_model: True # reprendre depuis le dernier meilleur modèle ?
device: "mps"
seed: 0
image_save_path: "sample1.png"

# paramètres de diffusion
n_steps: 1000
min_beta: 0.0001
max_beta: 0.02

# paramètres d'entraînement
batch_size: 128
n_epochs: 34
num_grid_rows: 10
lr: 0.0001
store_path: 'ddpm_mnist_ckptEpoch82.pth'
train_display: True

# paramètres UNET
unet_model: "unet_mnist" # unet_mnist pour mnist, unet_cifar pour cifar
time_emb_dim: 100


